
Регистрация и Авторизация<br><br><br>

Зарегистрироваться:<br><br>
<form action="/index/indexUser" method="post" enctype="multipart/form-data">
    ЛОГИН: <input type="text" name="name">
    Пароль: <input type="text" name="password"><br>
    Почта: <input type="text" name="email"><br>
    Возраст: <input type="number" name="age"><br>
    Файл: <input type="file" name="photo"><br>
    Описание: <input type="text" name="description"><br>
    <input type="submit" value="Register">
</form>

